version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=social
      - POSTGRES_USER=social
      - POSTGRES_PASSWORD=social
    volumes:
      - db-data:/var/lib/postgresql/data
    

volumes:
  db-data: