version: '3'

tasks:
  run:
    dir: cmd/api
    cmds: 
      - go run .

  up:
    cmds:
      - docker-compose up --build

  addmig:
    dir: cmd/migrate/migrations
    vars:
      MIG: '{{default "migration" .MIG}}'
    cmds:
      - goose -s create {{.MIG}} sql